#define SERIAL_USART_TX_PIN GP0

#define MATRIX_ROWS 10
#define MATRIX_COLS 7

#define MASTER_LEFT

#define MATRIX_ROW_PINS {GP12, GP13, GP14, GP15, GP26}
#define MATRIX_COL_PINS {GP3, GP4, GP5, GP6, GP7, GP8, GP2}

#define MATRIX_ROW_PINS_RIGHT {GP12, GP13, GP14, GP15, GP26}
#define MATRIX_COL_PINS_RIGHT {GP3, GP4, GP5, GP6, GP7, GP8, GP2}

//#define RGB_MATRIX_LED_COUNT 64
//#define RGB_MATRIX_SPLIT {32, 32}
//
////#define ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
//#define ENABLE_RGB_MATRIX_SOLID_COLOR
//
//#define RGV_MATRIX_DEFAULT_ON false
//
//#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 200
//#define RGB_MATRIX_DEFAULT_VAL 10
//
//#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_SOLID_COLOR
